import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import fs from 'node:fs';
const require=createRequire(import.meta.url);const{chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/86137/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const dir='docs/qa';fs.mkdirSync(dir,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'msedge'});
const context=await browser.newContext({viewport:{width:1600,height:900},deviceScaleFactor:1,recordVideo:{dir:dir+'/recordings',size:{width:1600,height:900}}});
const page=await context.newPage();const errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url())});
const ok=(name,extra)=>{checks.push({name,...extra});console.log('PASS',name)};
async function visit(name){await page.goto(`http://127.0.0.1:4173/${name}.html`);await page.waitForTimeout(950);}
async function stable(stage){await page.waitForFunction(id=>!document.getElementById(id).classList.contains('transitioning'),stage);}
async function noOverflow(){const s=await page.evaluate(()=>({w:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(s.scroll<=s.w+1,JSON.stringify(s));}
await visit('index');await noOverflow();await page.locator('#portals').scrollIntoViewIfNeeded();const cards=page.locator('.portal');const before=await cards.evaluateAll(es=>es.map(e=>e.getBoundingClientRect().width));await cards.nth(1).hover();await page.waitForTimeout(950);const after=await cards.evaluateAll(es=>es.map(e=>e.getBoundingClientRect().width));assert.ok(after[1]>(after.reduce((a,b)=>a+b)/2));const circle=await page.locator('.portal-disc').boundingBox();assert.ok(Math.abs(circle.width-circle.height)<1);ok('Home cards expand beyond 50%, squeeze siblings and retain circular geometry',{before,after});await page.screenshot({path:dir+'/home-hover.png'});
await page.locator('#aboutOpen').click();await page.waitForTimeout(800);assert.equal(await page.locator('dialog').evaluate(e=>e.open),true);await page.screenshot({path:dir+'/about.png'});await page.keyboard.press('Escape');assert.equal(await page.locator('#aboutOpen').evaluate(e=>e===document.activeElement),true);ok('About reveal, Escape and focus restoration');
await page.locator('#theme').click();await page.waitForTimeout(1100);assert.equal(await page.locator('html').getAttribute('data-theme'),'light');await page.screenshot({path:dir+'/home-light.png'});await page.locator('#language').click();await page.waitForTimeout(700);assert.equal(await page.locator('html').getAttribute('lang'),'en');await page.reload();await page.waitForTimeout(900);assert.equal(await page.locator('html').getAttribute('lang'),'en');assert.equal(await page.locator('html').getAttribute('data-theme'),'light');ok('Theme radial reveal, language switch and persisted settings');
await page.locator('nav a[href="./works.html"]').click();await page.waitForURL('**/works.html');await page.waitForTimeout(900);ok('Animated cross-page navigation');await noOverflow();await page.screenshot({path:dir+'/works-light-en.png'});
await page.locator('#theme').click();await page.waitForTimeout(1100);await page.locator('#language').click();await page.waitForTimeout(700);
for(let i=1;i<6;i++){await page.locator(`[data-project="${i}"]`).click();if(i===1){await page.waitForTimeout(100);const clip=await page.locator('.incoming').evaluate(e=>getComputedStyle(e).clipPath);assert.notEqual(clip,'none');await page.waitForTimeout(270);await page.screenshot({path:dir+'/works-transition.png'});}await stable('worksStage');assert.equal(await page.locator('.work-scene').count(),1);assert.equal(await page.locator('.project-rail .active').getAttribute('data-project'),String(i));const bounds=await page.locator('.crystal-open').boundingBox(),stage=await page.locator('#worksStage').boundingBox();assert.ok(bounds.y+bounds.height<=stage.y+stage.height+1,'project action clipped at '+i);}
ok('All six projects, transition initial frame, scene cleanup, action bounds');
await page.locator('[data-project="0"]').click();await stable('worksStage');await page.locator('.crystal-open').click();await page.waitForTimeout(850);
for(let i=0;i<6;i++){const shard=page.locator(`[data-shard="${i}"]`),b=await shard.boundingBox();await page.mouse.move(b.x+b.width*.3,b.y+b.height*.4);await page.waitForTimeout(300);const transform=await shard.locator('.crystal-tilt').evaluate(e=>getComputedStyle(e).transform);assert.ok(transform.startsWith('matrix3d'));const transparent=await shard.evaluate(e=>getComputedStyle(e).backgroundColor);assert.equal(transparent,'rgba(0, 0, 0, 0)');const visual=await shard.locator('.crystal-tilt').boundingBox();assert.ok(visual.x>=0&&visual.y>=0&&visual.x+visual.width<=1600&&visual.y+visual.height<=900);await shard.click();assert.equal(await shard.getAttribute('aria-pressed'),'true');}
await page.waitForTimeout(950);await page.mouse.move(30,30);await page.waitForTimeout(300);await page.screenshot({path:dir+'/crystals-back-final.png'});ok('6/6 crystal hit areas transparent, independent 3D, flip and viewport bounds');await page.keyboard.press('Escape');
await visit('experience');const startScroll=await page.evaluate(()=>scrollY);await page.mouse.move(800,400);await page.mouse.wheel(0,300);await stable('experienceStage');assert.equal(await page.locator('.timeline-rail .active').getAttribute('data-node'),'1');assert.equal(await page.evaluate(()=>scrollY),startScroll);await page.mouse.wheel(0,300);await stable('experienceStage');assert.equal(await page.locator('.timeline-rail .active').getAttribute('data-node'),'2');await page.keyboard.press('ArrowLeft');await stable('experienceStage');assert.equal(await page.locator('.timeline-rail .active').getAttribute('data-node'),'1');ok('Experience wheel navigation, unchanged page scroll and reverse keyboard navigation');await page.screenshot({path:dir+'/experience-final.png'});
await visit('life');for(const mode of ['dark','light']){if(await page.locator('html').getAttribute('data-theme')!==mode){await page.locator('#theme').click();await page.waitForTimeout(1100);}for(let i=0;i<4;i++){await page.locator(`[data-life="${i}"]`).click();await page.waitForTimeout(850);await page.screenshot({path:`${dir}/life-detail-${i}-${mode}.png`,fullPage:true});const dialog=page.locator('dialog');assert.equal(await dialog.evaluate(e=>e.open),true);assert.ok(await page.locator('#dialogTitle').innerText());await page.keyboard.press('Escape');}ok('Four distinct Life details: '+mode);}
await page.setViewportSize({width:390,height:844});
for(const name of ['index','works','experience','life']){await visit(name);await noOverflow();await page.screenshot({path:`${dir}/${name}-mobile-light.png`,fullPage:true});if(name==='works'){await page.locator('.crystal-open').click();await page.waitForTimeout(850);for(let i=0;i<6;i++){const s=page.locator(`[data-shard="${i}"]`);const b=await s.boundingBox();assert.ok(b.x>=0&&b.y>=0&&b.x+b.width<=390&&b.y+b.height<=844);await s.click();}await page.waitForTimeout(900);await page.screenshot({path:dir+'/crystals-mobile.png'});await page.keyboard.press('Escape');}ok(name+' mobile 390px without horizontal overflow');}
await page.setViewportSize({width:1280,height:720});await visit('works');await noOverflow();await page.screenshot({path:dir+'/works-1280.png'});ok('1280x720 layout');
await context.close();
const perfContext=await browser.newContext({viewport:{width:1600,height:900}});const perf=await perfContext.newPage();await perf.goto('http://127.0.0.1:4173/works.html');await perf.waitForTimeout(1200);
const metrics=await perf.evaluate(async()=>{const deltas=[];let previous=performance.now();let running=true;const cb=time=>{if(!running)return;deltas.push(time-previous);previous=time;requestAnimationFrame(cb)};requestAnimationFrame(cb);document.querySelector('[data-project="1"]').click();await new Promise(r=>setTimeout(r,1800));document.querySelector('[data-project="2"]').click();await new Promise(r=>setTimeout(r,1800));running=false;const sorted=deltas.slice(1).sort((a,b)=>a-b);return{samples:sorted.length,medianFrameMs:sorted[Math.floor(sorted.length*.5)],p95FrameMs:sorted[Math.floor(sorted.length*.95)],over50ms:sorted.filter(x=>x>50).length};});ok('Performance sampled without video recording',{metrics});await perfContext.close();
const reduceContext=await browser.newContext({reducedMotion:'reduce'});const rp=await reduceContext.newPage();await rp.goto('http://127.0.0.1:4173/works.html');await rp.locator('[data-project="1"]').click();await rp.waitForTimeout(100);assert.equal(await rp.locator('.work-scene').count(),1);assert.equal(await rp.locator('.project-rail .active').getAttribute('data-project'),'1');ok('Reduced motion keeps navigation functional');await reduceContext.close();
assert.deepEqual(errors,[]);ok('No console exceptions or failed resource requests');
fs.writeFileSync(dir+'/audit.json',JSON.stringify({date:new Date().toISOString(),browser:browser.version(),checks,errors,metrics},null,2));await browser.close();console.log('AUDIT COMPLETE',checks.length);
